x=10
try:
    print(x) 
except: 
    print("Something went wrong") 
finally: 
    print("The 'try except' is finished")